using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Entities
{
    public class CustomerBasket
    {
        public CustomerBasket()
        {
        }

        public CustomerBasket(string id)
        {
            Id = id;
        }

        public string Id { get; set; } // we are not putting it in the db , we put it in Redis. It is string because of that and because that it will be generated by the Angular
        public List<BasketItem> Items { get; set; } = new List<BasketItem>();
        
        // It should be optional because , at the moment user is creating the basket,
        // we yet do not have access to the deliverymethod from the checkout component 
        public int? DeliveryMethodId { get; set; }

        public string ClientSecret { get; set; } // used by stripe to confirm user payments
        public string PaymentIntentId { get; set; } // used for update the payment (ex: client change the delivery method)

        // We add this property for keeping the information regaaarding shippingDelivery price everythime -- even when we reload the window 
        public decimal ShippingPRice {get;set;}
    }
}